---
# these tasks install http and the php modules.

- name: Install httpd packages and php too
  action: yum name={{ item }} state=installed
  with_items:
   - httpd
   - php    

  notify:
   - Start Httpd
